version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://db:27017/mydb
    depends_on:
      - db

  db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
